theme: jekyll-theme-minimal
title: Amritha Vardhini Ravuri
logo: /assets/img/logo.png
description: amritha.v.ravuri@gmail.com \n I’m a Software Developer at Factset with two years of experience developing web-applications. I’m passionate about problem solving and creating long-term value for the customer by solving real-world problems.
